const countryList = {
    AED: "AE",
    AFN: "AF",
    XCD: "AG",
    ALL: "AL",
    AMD: "AM",
    ANG: "AN",
    AOA: "AO",
    AQD: "AQ",
    ARS: "AR",
    AUD: "AU",
    AZN: "AZ",
    ILS: "IL",
    INR: "IN",
    IQD: "IQ",
    USD: "US",
    RUB: "RU",
    EUR: "FR",
    PKR: "PK",
    JPY: "JP",
}